# Le fichier app.yaml définit l'application Node.js
name app
type nodejs18

relationships
  database dbpostgresql

dependencies
  npm {}

hooks
  build 
    npm install
    npm run build
  deploy 
    npm run start

# Assurez-vous que le port est bien 5000 comme configuré dans votre code
web
  upstream apphttp